### ISSUE TITLE
How to check palm rejection status

### ISSUE THREAD

**Issue by FrauH0lle** [virtualguywithabowtie/surface-orientation#2]
The palm rejection appears to work but it seems that it is always on. As soon as the stylus is in close proximity to the screen, touch input appears to be deactivated.
Is there away to display the status of the touch and pen input? Similar to the script https://github.com/AykoPoel/surface3-scripts ?

**Comment by JefeDavis** [comment]
can you verify that palm rejection isn't working without orientation running? it could be working without scripts help

**Comment by FrauH0lle** [comment]
You're right. That's interesting, did not know that this works "out of the box".

**Comment by JefeDavis** [comment]
If that's the case I may just remove it
